// <auto-generated />
using API.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20220226224626_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 3L,
                            CategoryName = "T-Shirt",
                            Description = "Camisa",
                            ImageUrl = "https://previews.123rf.com/images/happyjob/happyjob1608/happyjob160800122/62039034-.jpg",
                            Name = "Camisa",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "T-Shirt",
                            Description = "Camisa",
                            ImageUrl = "https://previews.123rf.com/images/happyjob/happyjob1608/happyjob160800122/62039034-.jpg",
                            Name = "Camisa",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "T-Shirt",
                            Description = "Camisa",
                            ImageUrl = "https://previews.123rf.com/images/happyjob/happyjob1608/happyjob160800122/62039034-.jpg",
                            Name = "Camisa",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "T-Shirt",
                            Description = "Camisa",
                            ImageUrl = "https://previews.123rf.com/images/happyjob/happyjob1608/happyjob160800122/62039034-.jpg",
                            Name = "Camisa",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "T-Shirt",
                            Description = "Camisa",
                            ImageUrl = "https://previews.123rf.com/images/happyjob/happyjob1608/happyjob160800122/62039034-.jpg",
                            Name = "Camisa",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "T-Shirt",
                            Description = "Camisa",
                            ImageUrl = "https://previews.123rf.com/images/happyjob/happyjob1608/happyjob160800122/62039034-.jpg",
                            Name = "Camisa",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "T-Shirt",
                            Description = "Camisa",
                            ImageUrl = "https://previews.123rf.com/images/happyjob/happyjob1608/happyjob160800122/62039034-.jpg",
                            Name = "Camisa",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "T-Shirt",
                            Description = "Camisa",
                            ImageUrl = "https://previews.123rf.com/images/happyjob/happyjob1608/happyjob160800122/62039034-.jpg",
                            Name = "Camisa",
                            Price = 69.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
